### ISSUE TITLE
Click on progress bar as well as drag.

### ISSUE THREAD

**Issue by joshuaiz** [lhz516/react-h5-audio-player#1]
Hello,

Really like this player - nice and customizable.

Was trying to implement clicking event so that when you click on the progress bar, the indicator moves to that location and the play progress is updated.

Here's what I have but the slider indicator position is incorrect so maybe you can help:

```javascript
bar.addEventListener('click', e => {
    console.log('bar clicked!')
    const target =
        e.target.nodeName === 'DIV' ? e.target.parentNode : e.target
    const width = target.clientWidth
    const rect = target.getBoundingClientRect()
    const offsetX = e.clientX - rect.left
    const duration = this.audio.duration
    const audio = this.audio
    const currentTime = (audio.duration * offsetX) / width

    this.setState({
        currentTime,
        duration,
        // barWidth,
        dragLeft: offsetX
    })
})
```

I think my math is wrong somewhere so hopefully you can point the way forward.

Thanks!

**Comment by lhz516** [comment]
Thanks. This is definitely something in the roadmap. I'll implement this feature soon.

**Comment by lhz516** [comment]
Feature added in https://github.com/lhz516/react-h5-audio-player/commit/af1e9f0b9c57cb5c4148653523660ba17915ca67
