### ISSUE TITLE
Can't seem to get the styles to work

### ISSUE THREAD

**Issue by raindecastro** [lhz516/react-h5-audio-player#100]
I'm using GatsbyJS and I can't seem to import the styles properly. I tried creating a separate scss file and manually add the classnames but when I check out the debugging tool and looked at the scss file that I imported, other classnames are working and the classnames for the music player is not showing up.

Can anyone give me direction please?

![scss file](https://user-images.githubusercontent.com/22409044/110507367-e8473880-813a-11eb-84e2-08561e4b5ada.png)
![file in chrome debugger](https://user-images.githubusercontent.com/22409044/110507379-ebdabf80-813a-11eb-8c97-bdeb772ab41e.png)

**Comment by lhz516** [comment]
I'm pretty sure there's nothing to do with this library. Maybe you can ask this question in GatsbyJS related repo?

**Comment by raulalgo** [comment]
Same thing was happening to me. I was forgetting to import the styles.css of the player. Make sure you have these two lines in your imports:

`import AudioPlayer from "react-h5-audio-player";
import "react-h5-audio-player/lib/styles.css";`
