### ISSUE TITLE
Volume knob going past end of volume bar

### ISSUE THREAD

**Issue by l0gicgate** [lhz516/react-h5-audio-player#102]
**Describe the bug**

The volume knob dimensions aren't being accounted for when the calculations are computed resulting in the knob being able to go past the end of the volume bar.

<img alt="volume 1" src="https://puu.sh/Hq1tV/648471fac1.png">

<img alt="volume 1" src="https://puu.sh/Hq1ua/2f61ac48d1.png">

**Environment**

Package version: Latest
React version: 17
Browser and its version: All Browsers
OS and its version: All OS

**Comment by l0gicgate** [comment]
For anyone looking for a short term fix:
```js
useLayoutEffect(() => {
  const volumeKnob = containerRef.current.querySelector(
    '.rhap_volume-indicator'
  );
  const offset = volume * volumeKnob.offsetWidth;
  volumeKnob.style.marginLeft = `-${offset}px`;
});
```

**Comment by lhz516** [comment]
The start/end of the bar is designed to align with the indicator's **center**. Feel free to overwrite it if you don't like it.

**Comment by l0gicgate** [comment]
> Feel free to overwrite it if you don't like it.

It can't be overwritten with CSS.. if you do for example `transform: translateX(-50%) it will put the knob too far behind the bar on the left side and be okay on the right side. 

The only way to do it right now is with the hook I showed above but that's super hackish. Would you be open to introducing an option for the volume knob so the user can control how they want the knob to be positionally? I can contribute the feature

**Comment by lhz516** [comment]
I'm ok with introducing a new prop that enables the new knob positioning. You can reopen the issue if you want to contribute it. `isKnobInsidePregressBar` sounds a good prop name. Feel free to propose another better name.

Please also ensure the click event near progressbar's beginning and end works properly.
