### ISSUE TITLE
Volume progress bar is not updating on changing volume value after sometime

### ISSUE THREAD

**Issue by curefit-prathibha** [lhz516/react-h5-audio-player#103]
**Describe the bug**

I tried to change the value of volume prop after the audio player is rendered. But the volume progress bar is not automatically adjusting to the new value. It is still showing progress as 1 only. The progress bar is only updating if we click on the control and change it, whereas it should be updated on changing volume prop as well.

**Environment**

Package version: 3.6.1
React version:
Browser and its version:
OS and its version:

**Comment by lhz516** [comment]
The `volume` prop's behavior is the same as the native attribute, so it only sets the **initial** value.

If you want to change the volume programmatically, you should get the `ref` and set `audio.volume = 0.5`;
