### ISSUE TITLE
rewind doesn't work correctly in IOS

### ISSUE THREAD

**Issue by makeoverweb** [lhz516/react-h5-audio-player#105]
**Describe the bug**

when you rewind before pressing the play button, the time display does not work.
https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts--default-story
you can see this if you log in from an iOS device and rewind first.The current time value will not change.
as I understand it this does not work due to the fact that iOS does not allow you to download the file until you click on the play button

**Environment**

Package version: 3.6.1
React version: 16.12.0

**Comment by lhz516** [comment]
Hi, I just tried it on Safari in iOS 14.1.1

What I found was that when I dragged the knob before pressing the play button, the current time was always 00:00 while playing. I'll look into it later.

**Comment by lhz516** [comment]
Fixed and added `onChangeCurrentTimeError` prop. Released [v3.7.0](https://github.com/lhz516/react-h5-audio-player/releases/tag/v3.7.0)

Closing the issue. Feel free to continue the discussion if needed.

**Comment by makeoverweb** [comment]
Thank you, that's enough for now!
