### ISSUE TITLE
Override default keyboard listeners

### ISSUE THREAD

**Issue by mcunningham** [lhz516/react-h5-audio-player#108]
Hi there, 

Is there a way to override or remove some of the current keyboard listeners? Specifically, I already have some global up and down arrow key listeners and I am trying to find a way to remove the up and down arrow key listeners which control the volume when the player is focused. Is there a way to do this?

**Comment by lhz516** [comment]
Currently, there isn't a way to do it, but it's definitely a good suggestion. I'll add a prop to toggle key bindings soon

**Comment by lhz516** [comment]
Added `hasDefaultKeyBindings` prop and released [v3.7.0](https://github.com/lhz516/react-h5-audio-player/releases/tag/v3.7.0)

Closing the issue. Feel free to continue the discussion if needed.

**Comment by mcunningham** [comment]
@lhz516 awesome thank you for this!
