### ISSUE TITLE
How to pass custom icons? 

### ISSUE THREAD

**Issue by raphrstuff** [lhz516/react-h5-audio-player#112]
How should one pass custom icons? Looking at the customIcons Interface it only accepts type ReactNode. Doesnt this make it impossible to pass an icon as a componed svg or anything that can render an icon? The documentation unfortunately doesnt provide any context for this as it only shows "sampleIcon" beeing used as a variable. So far i can only get it to render strings or nothing at all. Any help would be greatly appreciated.

**Comment by lhz516** [comment]
It definitely supports `<svg>`. Can you give it a try and let me know if it works? Feel free to paste some code samples here.

**Comment by raphrstuff** [comment]
Thanks for your reply. Awesome Library by the way :). actually got it to work now using img tags directly in props:

```
customIcons={{
   forward: <img src={require('../images/icons/audio-player/forward-30.svg').default} />,
   rewind: <img src={require('../images/icons/audio-player/rewind-15.svg').default} />
}}
```

But I couldnt get it to work with anything like this:

```
import customForward from '../images/icons/audio-player/forward-30.svg'
import customRewind from '../images/icons/audio-player/rewind-15.svg'

customIcons={{
   forward: customForward,
   rewind: customRewind
 }}
```

It would always put just a string in like ."data:image/svg+xml;base64,PHN2ZyANCiAg.....". Maybe something to do with my webpack config? I am using Gatsby Frameworks Default config in case you are curious.

If i tried to export it as a component it would just ignore it and render nothing at all. Which I figured might be because the Interface only accepts ReactNode's?

**Comment by lhz516** [comment]
Ah, I was thinking about the `<svg>` tag like this:
```
<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
```
If it's a base64 format svg, I believe setting it to an `<img>`'s src attribute is a general solution.

If you use a React component here, it will render nothing at all because a component is either a function or class. You need to create an element using the component. For example, `forward: MyComponent` -> `forward: <MyComponent />`
