### ISSUE TITLE
preventDefault on TouchMovies

### ISSUE THREAD

**Issue by brandflugan** [lhz516/react-h5-audio-player#113]
**Describe the bug**
In devtools (and debugging on phone) an error is constantly thrown when moving the progress indicator.
The following error is thrown:
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/509356600721408

A clear and concise description of what the bug is, and how to reproduce. Screenshots are appreciated.
1. Open up devtools and hit "Toggle device toolbar".
2. Open console and start dragging the indicator
3. The error should now be shown

![ezgif-3-f6d06ba943ba](https://user-images.githubusercontent.com/8988485/118044111-855e6180-b376-11eb-827c-193a015590d9.gif)

**Environment**
Apache, production code

Package version:

React version:
17

Browser and its version:
Chrome 90

OS and its version:
Mac OS Catalina

**Comment by lhz516** [comment]
Does it happen only on `touchmove` or both `mousemove` and `touchmove`?

**Comment by lhz516** [comment]
Fixed and published [3.7.1](https://github.com/lhz516/react-h5-audio-player/releases/tag/v3.7.1)
