### ISSUE TITLE
Don't work buttons rewind/forward

### ISSUE THREAD

**Issue by doksel** [lhz516/react-h5-audio-player#116]
When I press rewind / forward or drag the progress bar the recording is played from the beginning

**Comment by jayjayjayjayjayjay** [comment]
What device does the occur on?

**Comment by lhz516** [comment]
Closing due to lack of information. Re-open if you provide more details.

**Comment by rajatpillai** [comment]
I am facing the same issue in Chrome, once its loaded then forward, backward and dragging some time does not work

**Comment by doksel** [comment]
> What device does the occur on?
> Edit: I've found to have issues on chrome and mobile platforms with rewind/forward and scrubbing using the progress bar. The functionality works fine on firefox
> Edit: So issues was my backend wasn't returning 206. Double check that your backend can return 206. `curl -H Range:bytes=16- -I URL`

This was due to the wrong URL I received from the backend

**Comment by rajatpillai** [comment]
> > What device does the occur on?
> > Edit: I've found to have issues on chrome and mobile platforms with rewind/forward and scrubbing using the progress bar. The functionality works fine on firefox
> > Edit: So issues was my backend wasn't returning 206. Double check that your backend can return 206. `curl -H Range:bytes=16- -I URL`
> 
> This was due to the wrong URL I received from the backend

This is not a backend issue because I am using an azure storage URL for the audio file URL.
