### ISSUE TITLE
Could you change the icons repo?

### ISSUE THREAD

**Issue by irodger** [lhz516/react-h5-audio-player#117]
My point is the package @iconify/icons-mdi in react-h5-audio-player dependencies is too large. 
It contains more than 21k files and my CD system trying to copy all of them, it takes much time, and with yarn install just die by timeout. 

I'm tried to search for alternative react audio players without icon dependencies, but it's a sad story.
You are using about ten icons from the package. 
I'm not sure, but maybe if you should try to import icons with brackets can be helpful or just copy needed icons to your repo.

I mean
was
`import pauseCircle from '@iconify/icons-mdi/pause-circle'`
will
`import { pauseCircle } from '@iconify/icons-mdi'`

See the screenshots below

@iconify/icons-mdi
![image](https://user-images.githubusercontent.com/10072256/125883918-7f0fe6af-5ae7-44e2-a110-961cee544981.png)

My CI/CD log
![image](https://user-images.githubusercontent.com/10072256/125883959-6c6d6cb0-e4db-4523-905b-f8c08b75e366.png)

**Comment by lhz516** [comment]
`import { pauseCircle } from '@iconify/icons-mdi'` actually bundles the entire icon library into the player.
`import pauseCircle from '@iconify/icons-mdi/pause-circle'` is on-demend import.

Maybe you can modify your CI/CD config to not copy the unnecessary files?

**Comment by irodger** [comment]
It's impossible. I can't access your player build settings from my CI/CD. I'm just used yarn install with -D and --verbose options to find a bottleneck of my build. 

And now my remote server must copy all Material UI Icon library one by one for about an hour for every pull request. 

A proof in a terminal
![image](https://user-images.githubusercontent.com/10072256/126052068-ae3e1145-43ae-494e-a4e1-9eafb976b792.png)

**Comment by lhz516** [comment]
I don't think it's a common issue. The icon package is just a few MBs. You may want to find a solution with your bundling tool.
