### ISSUE TITLE
Display time as 0:00

### ISSUE THREAD

**Issue by ucin3d** [lhz516/react-h5-audio-player#118]
I am using short audio clips and wondering if there is an option to display the time with just one digit for the minutes instead of two, so instead of 00:00 show 0:00.

**Comment by lhz516** [comment]
You can pass in `customProgressBarSection` prop and overwrite `CURRENT_TIME` and `DURATION` section with your own implementation.

**Comment by ucin3d** [comment]
Thanks!

**Comment by lhz516** [comment]
See the doc: https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts-advanced--custom-progress-bar-section

Just replace `RHAP_UI.CURRENT_TIME` with any react element. By the way, you can get the `audio.currentTime` from the `ref`
