### ISSUE TITLE
Forward, backward and dragging of player not working in chrome

### ISSUE THREAD

**Issue by rajatpillai** [lhz516/react-h5-audio-player#125]
**Player forward, backward and dragging is not working properly sometimes in chrome**

This happens when the player is launched for the first time in the browser with a new audio URL if I refresh, it works fine but on initial load, it doesn’t 
Sharing with you the screen recording of the bug below: 

https://user-images.githubusercontent.com/35248779/134940111-906490f0-76c3-42ab-801a-09ebc84870e0.mov

**Environment**

Package version:  3.6.0
React version: 16.13.1
Browser and its version: Chrome Version 93.0.4577.82 (Official Build) (x86_64)
OS and its version: Mac 11.5.2

**Comment by lhz516** [comment]
It didn't happen in the code pen example: https://codepen.io/lhz516/pen/dyGpmgP

I guess it's somehow related to the file format or network. What's the file format and size please?

**Comment by skeshavaa** [comment]
@rajatpillai you're not using the skip next/previous buttons, you need to enable them in order to click them

**Comment by goshmx** [comment]
Same behavior here 
React version: 16.13.1
Browser: Chrome

**Comment by lhz516** [comment]
@goshmx Can you fork this codepen and make a reproducible example? https://codepen.io/lhz516/pen/dyGpmgP

**Comment by lhz516** [comment]
Closing this. If any updates, feel free to reopen.
