### ISSUE TITLE
Feature request: add a class to the loop button and another class to indicate if the loop button is active/inactive

### ISSUE THREAD

**Issue by ptmkenny** [lhz516/react-h5-audio-player#126]
Thank you for this excellent package; already my audio player looks a lot better than the default Chrome player.

I'd like to change the color of the loop button when it is clicked (gray if the loop is not active, green if the loop is active).

I tried to find a way to do it with the existing classes, but it seems there aren't enough.  So, I'd like to request adding a class to the loop `<button>` and a second class when the button is active or inactive.  This would allow themers to easily distinguish between when the button is active or not.

**Comment by lhz516** [comment]
Thanks for the contribution. Published `3.7.2`
