### ISSUE TITLE
Add a CSS class to the play button to distinguish between paused/playing

### ISSUE THREAD

**Issue by ptmkenny** [lhz516/react-h5-audio-player#130]
I want to change the color of the play button when the user presses it.  Would you be ok with a PR that adds a class to the play/pause button so that we can change the color based on the playback state?

**Comment by lhz516** [comment]
Sounds good. Just make it similar to your last PR.
You can reuse the `isPlaying()` method for checking the state.

**Comment by lhz516** [comment]
Published `3.7.3` and updated README.

@ptmkenny I changed some naming for [BEM](http://getbem.com/naming/) conventions. Please see the updated class names in [README](https://github.com/lhz516/react-h5-audio-player#status-class-names)

Again, thanks for the contribution!
