### ISSUE TITLE
Player on Iphone environment ?

### ISSUE THREAD

**Issue by Camille1993** [lhz516/react-h5-audio-player#135]
Hello, 
Fisrt : thanks for developping this customisable audio player.

Next :  for a school project, we had to make a music app . We chose to do it mobile first.

It work on Android system but not when we try it on IOS.

Does exist a possibility to make the player work on IOS or it's just a option that I don't have see ?

Thanks for you answers

**Comment by lhz516** [comment]
It should work on iphone environment already. 

What happened when you tried to use it in iOS?

**Comment by Camille1993** [comment]
After having deployed our application, I can confirm that It work on IOS. 
In the end, our problem was due to our CSS
