### ISSUE TITLE
i18n bug: Forward and Mute button translations are not applied

### ISSUE THREAD

**Issue by JonasGerits** [lhz516/react-h5-audio-player#136]
Dear lhz516,

First of all thanks for expanding the library with the option to use custom translations for the component!

I immediately went ahead and tried to use the translations. It works for almost all buttons except for the Mute and Forward buttons. 
In the code I can see that the i18n translation is not used.

Could you please fix this?

Thanks in advance!

**Comment by lhz516** [comment]
Thanks for reporting! I just fixed it and published `3.8.1`
