### ISSUE TITLE
Not rendering current time and duration

### ISSUE THREAD

**Issue by tommymm** [lhz516/react-h5-audio-player#137]
**Describe the bug**

The current time and duration are not **always** displaying correctly. Sometimes it is showing the default  "--:--" and sometimes only the current time, depends on what browser you are using. This issue looks almost the same as this one [issue #94 ](https://github.com/lhz516/react-h5-audio-player/issues/94)

**Chrome:** 
- Loaded the page for the very first time, the current time and duration are not showing
- After a hard page refresh both the current time and duration are displayed correctly

**Firefox:**  
- Loaded the page for the very first time, the current time and duration are not showing
- Hard page refresh will stays the same without the current time and duration
- After the playing the audio, only the current time is showing

**Code:**
`<AudioPlayer 
      src={audioUrl}
      showJumpControls={false}
      customProgressBarSection={[
        <TextNew.PrimaryElegant dataTestid="date-title" element={ElementTypes.H3} cid="date-title">
          {title}
        </TextNew.PrimaryElegant>,
        RHAP_UI.VOLUME,
      ]}
      customControlsSection={[
        RHAP_UI.MAIN_CONTROLS,
        RHAP_UI.CURRENT_TIME,
        RHAP_UI.PROGRESS_BAR,
        RHAP_UI.DURATION,
      ]}
    />`

**Environment**

Package version: 3.8.1
React version: 16.12.0
Browser and its version: Chrome 96.0.4664.45 / Firefox 94.0.2
OS and its version: Windows 10 PRO

**Comment by lhz516** [comment]
Hi, I'm not able to reproduce your description through the codepen https://codepen.io/lhz516/pen/dyGpmgP
Could you try the link above and see if it works?

**Comment by tommymm** [comment]
Hi, Thanks for looking into this and providing the codepen example. It is indeed something within our codebase. It looks like the issue was due to the server side rendering which causes this side effect.

**Comment by carrych** [comment]
Hi guys, I want to share my case with server side rendering. We've had problems with full duration of audio file (it was  default "--:--"  all the time, until the file has been listened to fully). 
How problem was solved:
import AudioPlayer, { RHAP_UI } from "react-h5-audio-player";
...
   <AudioPlayer
            autoPlay={false}
            src={mpeg.url}
            showJumpControls={false}
            className="Player"
            preload="none"
            customProgressBarSection={[
              RHAP_UI.CURRENT_TIME,
              RHAP_UI.PROGRESS_BAR,
              RHAP_UI.DURATION,
            ]}
          />

Key pieces: preload should be "none" and you have to provide explicit settings for progress bar section.
             
This link: https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts-advanced--custom-progress-bar-section from @lhz516  helped me a lot to solve this.
