### ISSUE TITLE
Upgrade @iconify/react for React 17 support

### ISSUE THREAD

**Issue by stovmascript** [lhz516/react-h5-audio-player#138]
Would it be possible to upgrade `@iconify/react`? Their current release supports React 17.

<img width="827" alt="Screen Shot 2022-01-04 at 13 21 47" src="https://user-images.githubusercontent.com/14262802/148058367-36e1ffbd-c03e-4448-861d-039e8e98f2db.png">

**Comment by lhz516** [comment]
I haven't tried Yarn 2 yet. When we upgrade `@iconify/react` to 3.x, does it support both React 16 and 17 or just 17?

**Comment by stovmascript** [comment]
@lhz516 Sorry for the late reply, missed it somehow in my notifications.

I'm not sure, they no longer specify `react` in [their `peerDependencies`](https://github.com/iconify/iconify/blob/master/packages/react/package.json).

**Comment by lhz516** [comment]
Thanks for the clarification. That's reasonable. Let me work on it.

**Comment by lhz516** [comment]
published 3.8.2

**Comment by stovmascript** [comment]
Sweet! Thanks for taking the time.
