### ISSUE TITLE
Is it possible to load icons as a dev dependency instead of a regular dependency?

### ISSUE THREAD

**Issue by ptmkenny** [lhz516/react-h5-audio-player#139]
Happy new year 😊

I was checking my `node_modules` size and I realized that this module has a 97 MB dependency on the material design icons.

I checked [the docs for icons-mdi](https://www.npmjs.com/package/@iconify/icons-mdi), which give the example using `--save-dev`.

Why does this module include the icons as a regular dependency instead of as a dev dependency?

**Comment by lhz516** [comment]
Even if it's a devDependency, the module is still there, and the size won't change, right?

I think it doesn't matter because only the icon that being used will be bundled.

**Comment by ptmkenny** [comment]
I may be wrong, but my understanding is that if it is a devDependency, when I install with `npm install --prod` on my CD server, then the file will not be there, saving 97 MB.

Right now, `npm install --prod` for my app is ~600 MB, but 97 MB of this is `icons-mdi`, so I'd like to reduce it if possible.

**Comment by lhz516** [comment]
The icon library is directly used in the audio player. If you don't install it for production, won't there be any errors?

**Comment by ptmkenny** [comment]
Ok, that's what I didn't understand.  If the library has to be installed, I guess I'll write a bash script to delete the unnecessary icons.

Thanks for the response.

**Comment by ptmkenny** [comment]
In case it's helpful to anyone coming to this issue from Google, here's the one-liner I used to delete all the unnecessary icons, freeing up about 88 MB of space:

`find ../node_modules/@iconify/icons-mdi -maxdepth 1 ! -name "play-circle*" ! -name "pause-circle*" ! -name "skip-previous*" ! -name "skip-next*" ! -name "fast-forward*" ! -name "rewind*" ! -name "volume-high*" ! -name "volume-mute" ! -name "repeat*" -delete`
