### ISSUE TITLE
Controls do not reflect the mute status

### ISSUE THREAD

**Issue by haecksenwerk** [lhz516/react-h5-audio-player#140]
**Describe the bug**

When changing the 'muted' state via ```player.current.audio.current.muted=false``` the volume is set to 0 and returns to the previous level when unmuted, but the volume slider doesn't change its position and the speaker symbol is not crossed out then. When toggling the mute state by clicking on the speaker icon, the speaker is crossed out, and the volume slider changes its position accordingly.
Other props settings like ```player.current.audio.current.volume``` or ```player.current.audio.current.play``` or ```player.current.audio.current.pause``` change the volumeslider respectively the play button as expected.

A clear and concise description of what the bug is, and how to reproduce. Screenshots are appreciated.

**Environment**

Package version: "^5.0.0"
React version: 17.0.2
Browser and its version: Safari + Chrome
OS and its version: macOS

**Comment by lhz516** [comment]
Currently, when you click the mute button, it doesn't set `muted=true`, but sets `volume=0`. It was implemented this way because using two properties to control volume is confusing, so I just used `volume`, and ignored `muted` property.

If you need the volume slider to move all the way to the left, please just set `volume=0`. Is there any particular reason that you have to set `muted=true` here?

**Comment by haecksenwerk** [comment]
Having a ```muted``` property would simply avoid additional code that saves the current volume-level for 'unmute' but which is already there in the player component:

```
    const audio = this.audio.current

    if (this.props.muted) {
      audio.volume = 0
    } else {
      audio.volume = this.lastVolume
    }
```

**Comment by lhz516** [comment]
It's detecting the `muted` property on the component, but not support changing volume based on `ref` audio's `muted` attribute.

**Comment by haecksenwerk** [comment]
Okay, that makes sense. So, as you already suggested, I would just use the ```volume``` attribute for this purpose. Thanks for looking into this matter.
