### ISSUE TITLE
Feature: add option for stopping audio

### ISSUE THREAD

**Issue by d21d3q** [lhz516/react-h5-audio-player#141]
Feature for stopping audio (continous) stream (online radio).

Stopping audio would force stopping buffering, playing would reload src and play from the end.

Currently when one pauses player which plays stream, player continues to download stream, and resuming starts from previous moment.

This might require some hacks described in [this SO answer](https://stackoverflow.com/a/13302599)

**Comment by lhz516** [comment]
This player wasn't designed for streaming live audio at the beginning.

There would be much more stuff to consider besides the feature you mentioned, such as progressbar behavior.

If you have bandwidth to add live streaming audio support, feel free to create a PR.
