### ISSUE TITLE
Some audio files in https://archive.org do not work with `react-h5-audio-player` while on archive.org site they do work

### ISSUE THREAD

**Issue by raphael10-collab** [lhz516/react-h5-audio-player#144]
I'm not able to play the following audio file: https://archive.org/details/the-lord-of-the-rings-bbc-radio-drama/J.R.R.+Tolkien+-+The+Lord+of+the+Rings+Book+1-+The+Fellowship+of+the+Ring+-+Disc+2+-+04.+Track04.flac 
as well as other audio files found in https://archive.org for example: https://archive.org/details/theunbelievabletruth21-23/The+Unbelievable+Truth+(s21+e02).mp3

https://codepen.io/lhz516/pen/dyGpmgP

Why does this happen if on https://arghive.org site the podcast is playable and listenable with no issues at all?
How to make it work with `react-h5-audio-player`?

**Comment by lhz516** [comment]
The url ended with `.mp3` doesn't mean it's an mp3 file. It's actually a website url.

You need to inspect elements and go to the Network tab to find out the actual mp3 URL.
![image](https://user-images.githubusercontent.com/9879279/154780597-84ffa827-5f6c-4cae-badc-951f8358fad2.png)
