### ISSUE TITLE
Audio Player will NOT play 

### ISSUE THREAD

**Issue by gabrielshannon** [lhz516/react-h5-audio-player#154]
I have installed the package into a basic create-react-app and attempted to set up the component following the documentation provided. 

```
     <AudioPlayer
          autoPlay
          src="https://samplelib.com/lib/preview/mp3/sample-3s.mp3"
          onPlay={(e) => console.log("onPlay")}
          // other props here
        />
```

When changing the example URL out for a sample MP3 url the player does not appear to load the file and remains frozen. There are no errors that are logged. 

Unsure of how to get this to work?

**Comment by technophile-04** [comment]
Hey had the same issue try removing React.StrictMode

**Comment by gabrielshannon** [comment]
problem solved. 

Thank You
