### ISSUE TITLE
Is it possible to start the audio clip at a certain time?

### ISSUE THREAD

**Issue by bturner1273** [lhz516/react-h5-audio-player#155]
It would be useful for my application to be able to start an audio clip somewhere not at the beginning of the clip and/or jump to a specific point in time in the audio. Is this possible?

i.e. like a setProgress hook?

**Comment by lhz516** [comment]
Get the audio ref and set currentTime.

Eg. `this.player.current.audio.current.currentTime = 120`. See the advanced usage section in the doc.

**Comment by sgarchavada** [comment]
@lhz516 where is the doc? can you share a link here?
