### ISSUE TITLE
Fade In / Fade Out

### ISSUE THREAD

**Issue by Simoneth** [lhz516/react-h5-audio-player#156]
Hi,
Very nice player!

Could you please implement a fade in / fade out mechanism? 
It will be cool, especially for playlists.

**Comment by lhz516** [comment]
I guess it's out of scope. You can add fade in/out by dynamically changing the container's class names, right?

**Comment by Simoneth** [comment]
I meant the audio track fade in / fade out, but yes it's difficult I guess...
