### ISSUE TITLE
Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.

### ISSUE THREAD

**Issue by Simoneth** [lhz516/react-h5-audio-player#157]
**Describe the bug**

Playing a list of songs, `onEnded`, I get this warning: `Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.`

**Environment**

Package version: 3.8.4
React version:17.0.2
Browser and its version:Chrome 102
OS and its version:Mac

**Comment by lhz516** [comment]
Are you calling `audio.play()` in `onEnd`? Actually you can just set new `src` to play the next song.

In the storybook, there's a [playlist example](https://github.com/lhz516/react-h5-audio-player/blob/c67726b047adc05d4f63f592d869e9d4b025310c/stories/playlist.tsx).

**Comment by Simoneth** [comment]
Here is the function I call `onEnded`:

```
    const handleClickNext = () => {
        setTrackIndex((currentTrack) =>
            currentTrack < musicTracks.length - 1 ? currentTrack + 1 : 0
        );
    };
```

And the `musicTracks` array is something like this:
```
[
    {
        "name": "juino",
        "src": "https://bit...29861/1.mp3",
        "id": "f98cdecf-fb63-484c-85a1-068158e1eabb"
    },
    {
        "name": "delta25",
        "src": "https://bit...31535/1.mp3",
        "id": "a484075a-6920-4f13-ad18-203b64dc4f90"
    }
]
```

**Comment by lhz516** [comment]
I tried in codepen and didn't find any issues. https://codepen.io/lhz516/pen/ZExvXjx

Please fork the link above and reproduce the issue if it's not resolved.
