### ISSUE TITLE
Live Demo and Website is down

### ISSUE THREAD

**Issue by liamc1011** [lhz516/react-h5-audio-player#158]
I'm trying to access the [Live Demo](https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts--default-story) and the [Custom icons](https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts--custom-icons) link in the README, but the website [hanzluo.com](hanzluo.com) seems to be down.
Is there any way to get the site back up or to view (what I'm assuming is) the documentation regarding usage of custom icons and custom layout?

**Comment by lhz516** [comment]
I'll use Github page instead.

**Comment by eltel** [comment]
+1, please! :)

**Comment by lhz516** [comment]
Here you go: https://lhz516.github.io/react-h5-audio-player

**Comment by eltel** [comment]
> Here you go: https://lhz516.github.io/react-h5-audio-player

THis is awesome, thanks so much!
