### ISSUE TITLE
Multiple Audio Players With Different Progress Indicators?

### ISSUE THREAD

**Issue by liamc1011** [lhz516/react-h5-audio-player#161]
I am attempting to have multiple audio players on the same page, and have each audio player be a different color. 

I can easily control the border and background colors of each player using the `style` prop, however I can't figure out a way to have different `progress-indicator` (and `progress-filled`) colors. 
I am able to overwrite the default gray color by applying my own stylesheet, but this changes the `progress-indicator` color for every single audio player, and not just one. 

Is it possible to have multiple audio players with different colored progress indicators, or is this not possible due to how React H5 Audio Player is structured?
If not possible, could this feature be viably added?

**Comment by lhz516** [comment]
Pass a custom `className` into a wrapper:
```jsx
<AudioPlayer className="player1" />
```
And overwrite the child class:
```scss
.player1 .rhap_progress-indicator {
  // your custom style
}
```

**Comment by liamc1011** [comment]
thank you so much!
