### ISSUE TITLE
onError doesn't work on mobile

### ISSUE THREAD

**Issue by matteomontipo** [lhz516/react-h5-audio-player#167]
**Describe the bug**

onError doesn't work on mobile. It's working correctly on desktop, it fires a function, but on mobile nothing happens.
I'm using next.js + next-pwa if can be of any help

**Environment**

Package version: 3.8.4
React version: 18.2.0
Browser and its version: Chrome latest
OS and its version: Android

UPDATE:
Found the issue, you can close this. thank you

**Comment by lhz516** [comment]
Closing as you already found the issue.
