### ISSUE TITLE
Button Play doesn't work

### ISSUE THREAD

**Issue by krono999** [lhz516/react-h5-audio-player#169]
hello, im using the audio player, the button next and previous work well but, when i open at the first time or reloaded the web, the button play doesn't load and play the first song, only works if i clicke previous or next.
other doubt: i test the code in stackblitz with the code example and it works! and is the same i use in this example, but in my localhost doesnt work
please help me :(

here is my code:

import { useState } from "react";
import AudioPlayer from "react-h5-audio-player";
import "react-h5-audio-player/lib/styles.css";

export default function AudioPlayerComponent() {
  const musicTracks = [
    {
      name: "song1",
      src: "https://res.cloudinary.com/mp3", // only for the example
    },
    {
      name: "song2",
      src: "https://res.cloudinary.com/mp3", // only for the example
    },
  ];

  const [trackIndex, setTrackIndex] = useState(0);

  const handleClickPrevious = () => {
    setTrackIndex((currentTrack) =>
      currentTrack === 0 ? musicTracks.length - 1 : currentTrack - 1
    );
  };

  const handleClickNext = () => {
    setTrackIndex((currentTrack) =>
      currentTrack < musicTracks.length - 1 ? currentTrack + 1 : 0
    );
  };

  return (
    <div className="audio">
      <AudioPlayer
        style={{
          backgroundColor: "transparent",
          color: "purple",
          fontFamily: "monospace",
          marginTop: "-70px",
          fontSize: "15px",
        }}
        src={musicTracks[trackIndex].src}
        onPlay={musicTracks[trackIndex].src}
        showSkipControls={true}
        showJumpControls={false}
        header={`Now playing: ${musicTracks[trackIndex].name}`}
        onClickPrevious={handleClickPrevious}
        onClickNext={handleClickNext}
        onEnded={handleClickNext}
      />
    </div>
  );
}

**Comment by lhz516** [comment]
Please fork the codepen example in README to reproduce this error, then I can take a look.

**Comment by BrianEmilius** [comment]
I have the same issue - it looks like src isn't loaded properly during first render in dev-mode.

Here's an example of it not working:
https://github.com/BrianEmilius/react-player-example/blob/main/src/App.js

**Comment by BrianEmilius** [comment]
I should add that it works in production (after build), just not in development mode (npm start)

**Comment by totti-rdz** [comment]
Interesting, while investigating another problem I noticed that on localhost I can not play the audio file.

I also added an onPlay function, that just logs the clicking of the button, but apparently it does not even trigger, so the button is not clicked at all.

https://react-h5-audio-player.vercel.app/
https://github.com/totti-rdz/react-h5-audio-player

**Comment by krono999** [comment]
i dont have codepen or sandbox account, the issue is like i said, you press button plan when you are developing the app in your local but doesnt work, but the other two button works well. i put the code example.
i saw other example like stack blitz, and put my code in that web examples and my code works! xD I dont know what is the problem honstely

**Comment by krono999** [comment]
i see the code of brian and is bit similar of mine and he had the same problem

**Comment by ferdiamg** [comment]
This package has the same problem as all other not updated packages right now.
Due to React 18 running useEffect twice with reactStrictMode enabled, something in this package got broken. Disable the strictMode and it'll run just fine. However its not recommended to just switch off the strictMode for a npm package.

**Comment by lhz516** [comment]
The original idea of removing `src` attribute while unmount is to stop the audio from playing when the player is removed from the DOM. If we remove this line, we need some similar features. 

I'm considering using `audio.pause()` at the unmount lifecycle. Any opinions?

**Comment by totti-rdz** [comment]
Interesting, that the audio player would keep playing after the component gets unmounted. Do you have more info on that?

I think replacing the function to remove src with audio.pause() function is a valid solution.

**Comment by lhz516** [comment]
Oh never mind, I just tested it and found that the audio won't stop when the component is destroyed. Let me just remove this line

**Comment by lhz516** [comment]
Published 3.8.6
