### ISSUE TITLE
[Question] Is it possible to get mimetype of an audio src?

### ISSUE THREAD

**Issue by Deveshb15** [lhz516/react-h5-audio-player#170]
I wanted to get the mime-type of the audio file currently being played, have used mime package and sent audio ref to the args with different variations like `audio.current` and `audio.current.audio.current` but none of them worked, any ideas or workaround?

**Comment by lhz516** [comment]
It's the server's responsibility to provide the mimetype via `Content-Type` header. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

Some libraries use file extensions to determine MIME type, but it's not quite reliable.

**Comment by Deveshb15** [comment]
Got it, thanks:)
