### ISSUE TITLE
[Question] Is it possible to get of an remote audio once loaded?

### ISSUE THREAD

**Issue by Deveshb15** [lhz516/react-h5-audio-player#175]
Is it possible to get of an remote audio once loaded using ref or an internal function as you already show it in the UI on the player

**Comment by lhz516** [comment]
It's currently not supported. May I know why you need this usecase?

**Comment by Deveshb15** [comment]
Wanted to discard songs below 12-15 secs as they are usually spam

any workaround would also be good?

**Comment by lhz516** [comment]
You can create an audio object manually, and access `audio.duration`.

If it fits the condition, render the audio player with the src.
![image](https://user-images.githubusercontent.com/9879279/190838153-363a88f2-3d0b-47a0-800b-639e846a0ebe.png)

**Comment by Deveshb15** [comment]
Got it, thanks:)
