### ISSUE TITLE
V2 Features

### ISSUE THREAD

**Issue by lhz516** [lhz516/react-h5-audio-player#18]
Thanks all for supporting this project. I haven't thought about this library can get more than 1000 downloads per week. That makes me feel I have the responsibility to make it better.

Here are V2.0.0 features I'm proposing:
- [x] Stop using inline style. Use external `scss` instead. (Pure `css` will also be provided.)
  - Developers will be able to overwrite `scss` variables to overwrite styles
- [x] Add options to enable/disable "Previous" and "Next" button, `onClickPrevious` and `onClickNext` will also be supported. However, a playlist component won't be included, developers need to implement their own playlist component, because I want this library to be more focus on the player itself
- [x] Add option to enable/display "Volume" control, because volume won't be supported on some mobile OSs
- [x] A11y support

Other features TBD. Feel free to discuss about it.

**Comment by gencer** [comment]
Thank you for your continuing support on this project.

Especially inline/SCSS part will be a good improvement.

**Comment by gencer** [comment]
Forgot to mention. One more addition from me:

- An ability to give icons via Font (Like FontAwesome or IonIcons) for play, pause and stop buttons instead of CSS tricks.

**Comment by lhz516** [comment]
@gencer Hi, I'm using [iconify-react](https://github.com/iconify/iconify-react) for icons in V2. It's a lightweight react wrapper for SVG icons.

https://github.com/lhz516/react-h5-audio-player/blob/v2/src/index.js

`Material Design Icons` provide a lot of great icons. We may not need custom icons.

Thanks for your suggestion!

**Comment by lhz516** [comment]
🚀
