### ISSUE TITLE
The color of the buttons color can not be changed 

### ISSUE THREAD

**Issue by NAJIB-B** [lhz516/react-h5-audio-player#180]
The color of the buttons color can not be changed, even though they can be replaced with icons, the progress bar can not be replaced

**Comment by lhz516** [comment]
Doesn't overwriting styles work? Please add more details.

To replace progress bar, you can still use `background-image` on the progressbar CSS class

**Comment by lhz516** [comment]
Closing it. Feel free to reopen if you need some followup discussion.
