### ISSUE TITLE
Vertical volume audio bar

### ISSUE THREAD

**Issue by felipebelinassi** [lhz516/react-h5-audio-player#186]
Hello!

I'm using the library in my project and I really like it. However, I noticed that the volume audio bar is only scrollable horizontally.
I was wondering if it is possible to configure the volume audio bar to be scrollable vertically instead, or if this is something that could be implemented in a future update.

In the end it would look like this:
<img width="50" alt="image" src="https://user-images.githubusercontent.com/16722706/207138916-ae212bd1-21fa-4ef0-902b-a868719589ba.png">

Thank you in advance!

**Comment by lhz516** [comment]
Closing it. Feel free to reopen if you need some followup discussion.
