### ISSUE TITLE
playing multiple audios 

### ISSUE THREAD

**Issue by imyosh** [lhz516/react-h5-audio-player#188]
Is there an option so that only one audio can be played at a time when rendering multiple audio elements ? so that when user click play to one the others set to pause state

**Comment by lhz516** [comment]
You can save all the audio refs to one place, and when setting one of the audio to play, set all other audios to pause in the `onPlay` callback. The player UI will be automatically updated when you do `audio.pause()` method.

**Comment by lhz516** [comment]
Closing it. Feel free to reopen if you need some followup discussion.
