### ISSUE TITLE
Multi line song name as marquee tag in header

### ISSUE THREAD

**Issue by shaikhjafar779** [lhz516/react-h5-audio-player#189]
If song name is in a singe line in header its works fine.
But when song name is of 2 or multi lines, can we have that song name as a marquee tag or something else better.

**Comment by lhz516** [comment]
The `header` property is a `ReactNode` type which basically supports everything. However, I noticed the `marquee` tag is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee). You may want to consider another solution.

**Comment by lhz516** [comment]
Closing it. Feel free to reopen if you need some followup discussion.

**Comment by shaikhjafar779** [comment]
So, what will be the solution if I want to make song name animated from right to left just like marquee tag.

**Comment by lhz516** [comment]
You may want to search for some CSS animation, or use JS + CSS to control the animation
