### ISSUE TITLE
Audio loading progress bar

### ISSUE THREAD

**Issue by 12enn** [lhz516/react-h5-audio-player#190]
HI, Thanks for sharing nice library for playing audio.
Could you let me know if this library supports  to show Audio loading progress bar?
And how to  show the percentage 
 I want to use the Audio loading progress bar,  
if( percentage =100% ){

show the playing audio
}

**Comment by shaikhjafar779** [comment]
Hello,
Use showDownloadProgress={true} prop for audio loading progress.
It is mentioned in document also. [Document link here](https://github.com/lhz516/react-h5-audio-player#uiux-props)

**Comment by 12enn** [comment]
Thank you,I would like to ask one more question,How do I call this onplay method in a react component

**Comment by shaikhjafar779** [comment]
To call onPlay method in a react component [Refer this](https://github.com/lhz516/react-h5-audio-player#usage)

**Comment by 12enn** [comment]
thank you!

**Comment by lhz516** [comment]
@shaikhjafar779 Thanks for answering the question here! Closing as it's resolved.
