### ISSUE TITLE
React AudioPlayer not applying styles as default

### ISSUE THREAD

**Issue by Prabhat2373** [lhz516/react-h5-audio-player#191]
**Describe the bug**

While using AudioPlayer there is no styles and no props are working perfectly it's just playing music and showing some controlls.
![image](https://user-images.githubusercontent.com/76727816/221815844-a44ec268-bc83-4288-b302-413eec5d14e5.png)

![image](https://user-images.githubusercontent.com/76727816/221816323-cbbdc914-b2f5-45cf-9179-6a7fb3450b33.png)
@lhz516 

**Environment**

Package version:^3.8.6
React version:^18.2.0

**Comment by lhz516** [comment]
The README mentioned you need import the styles into the file. Also, your bundling tool like webpack needs to have proper loaders to bundle the styles

**Comment by Prabhat2373** [comment]
Yes, It Works!
Thanks for replay
