### ISSUE TITLE
Is there a way to change playback speeds ?

### ISSUE THREAD

**Issue by roeingg** [lhz516/react-h5-audio-player#203]
hi,
Is there a way to change playback speeds ?
Needed for me....

**Comment by lhz516** [comment]
You can use advanced layout to add custom UI and use `ref` to control the `audio` instance

https://lhz516.github.io/react-h5-audio-player/?path=/docs/layouts-advanced--stacked

**Comment by roeingg** [comment]
tnx 
added :)
