### ISSUE TITLE
The progress bar doesn't work when the layout changes.

### ISSUE THREAD

**Issue by vickvasquez** [lhz516/react-h5-audio-player#219]
**Describe the bug**

I found a bug when changing the layout and settings of the customProgressBarSection; the progress bar stops working. Below, I provide a demo and instructions on how to reproduce the bug.

Steps:
1.- Play music
2.- Click on stacked

Demo: https://codepen.io/vickvasquez/pen/WNPaqZY

**Environment**

Package version:  3.9
React version: 17.0.2
Browser and its version: 1.60.118 Chromium: 119.0.6045.163 (Build oficial) (x86_64)  
OS and its version:  macOS Monterey

**Comment by lhz516** [comment]
Yea I did reproduce that. Changing layout while playing an audio is not supported at this moment.
I actually think this is a rare usecase. Are you just testing it out or is it a real requirement for an application? If it's a real requirement, could you describe the usecase detail so that I can decide if this is something worth fixing?

**Comment by vickvasquez** [comment]
Hello @lhz516 , thank you for responding.

I'll tell you about it; I'm creating an application that has a music player. On mobile devices, this player needs to be maximized and minimized to provide a better user experience. This is where I change the layout because the design requires it.

I'm attaching a video for your reference.

https://github.com/lhz516/react-h5-audio-player/assets/5327805/9057cc9f-d7f3-4790-a6cb-6cffe4ef6388

**Comment by lhz516** [comment]
Thanks. That makes sense, but I currently don't have bandwidth to work on it until Jan. 2024. PRs are welcome as well

**Comment by lhz516** [comment]
It's actually an easy fix, and I just fixed it. Try `3.9.1`

**Comment by vickvasquez** [comment]
Thank so much, it's working
