### ISSUE TITLE
Feature Request: Volume Bar Color Separation

### ISSUE THREAD

**Issue by shafiReckon** [lhz516/react-h5-audio-player#221]
If the volume is between 0% (exclusive) and 100% (exclusive), I would like to have different colors for the volume bar to distinguish between the filled and unfilled portions. For instance, if my volume is set to 40%, I should be able to customize the color for the first 40% of the volume bar, while the remaining portion should be in a different color.

**Comment by lhz516** [comment]
Sounds reasonable. Adding it to my roadmap

**Comment by lhz516** [comment]
I almost forgot that there's already a prop `showFilledVolume` to display the filled volume. And then you can customize the `.rhap_volume-filled` for a different color.
