### ISSUE TITLE
Why is autoPlayAfterSrcChange set to true by default?

### ISSUE THREAD

**Issue by emao** [lhz516/react-h5-audio-player#224]
Is there a reason `autoPlayAfterSrcChange = true` by default? I was chasing down a bug where the player would randomly start playing even when `autoPlay = false`. Turns out the issue was this setting was enabled by default. I suspect my `src` sometimes flickers between set and unset when React renders.

It also doesn't respect the `autoPlay` setting by current design. I'd expect it to not `autoPlayAfterSrcChange` if `auto = false`

Wondering why this was the set default and if I'm missing a use case here. Thanks.

**Comment by lhz516** [comment]
I believe the reason would be backward compatibility concern.
