### ISSUE TITLE
ReferenceError: TouchEvent is not defined

### ISSUE THREAD

**Issue by Robstaa** [lhz516/react-h5-audio-player#23]
First of all, really great product!!
Using it on our website and it looks so nice and works really well (especially on mobile).
The only error we are getting from Sentry is 

`ReferenceError: TouchEvent is not defined`.

I tried to reproduce and found that on Desktop (Safari and Firefox) the progress bar cannot be controlled. Meaning that clicking or sliding the progress bar has no effect. Chrome works though.
Just wanted to know, if that issue is new to you or if maybe I did something wrong while implementing it. Thanks a lot!

**Comment by lhz516** [comment]
Thanks for reporting. I just checked MDN and found `TouchEvent` is not supported in FF < 52, Safari and IE.

I thought Babel would convert it, but actually not. Let me fix this.

https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent

**Comment by Robstaa** [comment]
Thanks a lot!! Really appreciate your work.

**Comment by lhz516** [comment]
Fixed. Try `2.3.5`

**Comment by Robstaa** [comment]
It works perfectly! Thank you so much - closing this.
