### ISSUE TITLE
multi-audio played at the same time

### ISSUE THREAD

**Issue by JackHuang16** [lhz516/react-h5-audio-player#29]
**Describe the bug**

it doesn't listen to the play function correctly, it causes multi-audio played at the same time.

<img width="488" alt="Screen Shot 2020-03-06 at 11 01 32 AM" src="https://user-images.githubusercontent.com/8913003/76046097-f992bd80-5f99-11ea-872b-b1a85766ac98.png">

**Environment**

Package version: 2.4.2
React version: ^16.12.0
Browser and its version: 

OS and its version:

**Comment by lhz516** [comment]
Every player has its own `Audio` reference. Starting to play one of them doesn't seem to affect others. I don't quite get why this happens.

You can see the live demo in README which has multi players and work properly, right?

Could you provide a minimal reproducible example using any online tool like jsfiddle?

**Comment by JackHuang16** [comment]
Understood, because I need only one player at the same time in my scenario.
Thanks for your reply.
