### ISSUE TITLE
Attribute "volume" is not allowed on element "audio"

### ISSUE THREAD

**Issue by Tawpie** [lhz516/react-h5-audio-player#3]
from the W3 validator:

```
Error: Attribute volume not allowed on element audio at this point.

From line 945, column 2098; to line 945, column 2218

<audio src="my.mp3" title="my.mp3" volume="1" preload="auto">

Attributes for element audio:
Global attributes
src — Address of the resource
crossorigin — How the element handles crossorigin requests
preload — Hints how much buffering the media resource will likely need
autoplay — Hint that the media resource can be started automatically when the page is loaded
loop — Whether to loop the media resource
muted — Whether to mute the media resource by default
controls — Show user agent controls
```

**Comment by edlerd** [comment]
i created a pull request to remove the volume tag: https://github.com/lhz516/react-h5-audio-player/pull/4

**Comment by lhz516** [comment]
@Tawpie @edlerd Thanks for pointing it out. I'm actually confused that even though volume attribute doesn't pass W3 validator, it still works. If you set the volume prop to any number between 0-1, it defines the initial volume of the player, isn't it?

**Comment by Tawpie** [comment]
Yeah—I haven’t actually tried to see if it does what one would expect, but so far devices (both as apps and using various browsers on iOS and Android) haven’t complained about it. I would suspect Apple would not want an app to fuss with the volume a user has set for their phone but don’t know that for certain. MDN doesn’t list volume as a valid attribute though so even if it doesn’t get removed it should at least be caveated as “may not be supported”.

**Comment by lhz516** [comment]
Working on v2. Volume control will be managed by a prop
