### ISSUE TITLE
When src changes and autoPlayAfterSrcChange is true , icon changes to pause.

### ISSUE THREAD

**Issue by camilo9497** [lhz516/react-h5-audio-player#30]
**How to reproduce it**
-Audio is pause or playing
-Click on skipControls
Audio starts or continues, but the icon changes to pause icon

**Expected**
Icon changes or continues to play icon

**Environment**

Package version: 3.0.0-rc.2
React version: 16.12.0
Browser and its version: Google Chrome  80.0.3987.132
OS and its version: Windows 10

**Comment by lhz516** [comment]
Good catch! Looks like the `audio.readyState` isn't reliable. Sometimes it returns `0` even if the audio already started playing.

I've removed that condition for playing state. Please try `3.0.0-rc.3` and let me know if it works

**Comment by camilo9497** [comment]
Yes, it works now
