### ISSUE TITLE
Player does not unmount on component change

### ISSUE THREAD

**Issue by moh3ni** [lhz516/react-h5-audio-player#33]
Hello,

It is maybe something I am doing wrong but I have to ask, I have tried a lot to fix this with no luck.

I have a list of tracks on browse component, when I click on one, player component with react-h5 player in it, It fetched the audio source with GraphQl and provide to react-h5, everthing working as expected but when I click on menu back to track lists, playing stops and I get this warning in console "index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method." . But if I use the Play/Pause button on keyboard the track plays again in background.
No warning when I pause the player and go back to track lists. But I can again use my keyboard to play the same track in the background. so the react-h5 does not unmount.

Thanks in advance

**Comment by lhz516** [comment]
I think it's fixed. Try 3.0.3

**Comment by moh3ni** [comment]
Thanks @lhz516 , it is fixed.
But it is still possible to play the recently played track with Play/Pause on the keyboard in the background after the player component is unmounted. it is maybe not a bug.

**Comment by lhz516** [comment]
@moh3ni  You brought up a very good point. I found that even if the audio/video dom element is destroyed, the audio/video object is still in memory:

https://stackoverflow.com/questions/3258587/how-to-properly-unload-destroy-a-video-element

I have reset the audio src when unmounting, could you try 3.0.4 and see if it's fixed?

**Comment by moh3ni** [comment]
still the same "problem", it maybe is something on my side

**Comment by lhz516** [comment]
`src` has been removed in `componentWillUnmount`, so even if the audio object is still there and runs `audio.play()`, nothing will happen.
https://github.com/lhz516/react-h5-audio-player/blob/f704fd51d3ee8839b7a3b866fcd881633a084402/src/index.tsx#L499
Let's close this for now. Feel free to reopen if you have any new findings.

**Comment by kqvanity** [comment]
@lhz516 
I've an extension that fetches lists of recordings (modeled an object for a recording containing title & url).
After using it for a while, I start getting [Media Decoder](https://discussion.fedoraproject.org/t/firefox-audio-issues-fails-to-play-audio-after-a-while/64887) issue. Apparently It has something to do with a file descriptors aka too many concurrent recordings in the context of firefox.

How can I call `componentWillUnmount`? all I have is setting attributes to `H5AudioPlayer` like the `src` attribute for example.
