### ISSUE TITLE
When used with form libraries, control buttons trigger form submission because of lack of type

### ISSUE THREAD

**Issue by johnfrommartin** [lhz516/react-h5-audio-player#34]
**Describe the bug**
Forms that have this audio player rendered, will trigger form submission when one of the main control buttons are clicked. 

<img width="1292" alt="Screen Shot 2020-04-14 at 3 02 04 PM" src="https://user-images.githubusercontent.com/61752255/79263498-ef00f900-7e60-11ea-95e6-51d0d68c5238.png">

```
Warning: You submitted a Formik form using a button with an unspecified `type` attribute.  Most browsers default button elements to `type="submit"`. If this is not a submit button, please add `type="button"`.
```

Can we have the type specified as `"button"` to prevent this from happening? `e.stopPropagation()` will not prevent this behavior from happening. 

Suggested Fix: 
```
<button
  aria-label={isPlaying ? 'Pause' : 'Play'}
  type="button" //  <-- Fix
  className="rhap_button-clear rhap_main-controls-button rhap_play-pause-button"
  onClick={this.togglePlay}
>
  {actionIcon}
</button>
```

**Environment**

Package version: `"react-h5-audio-player": "^3.0.4",`
React version: `"react": "^16.8.2",`
Browser and its version: Chromium
OS and its version: macOS Mojave 10.14.6 (18G95)

**Comment by lhz516** [comment]
Good catch! The use case inside a form hasn't been considered before.

Try 3.0.5

**Comment by johnfrommartin** [comment]
@lhz516 Works great, thanks!
