### ISSUE TITLE
How to remove border from UI elements that shows up after a click event

### ISSUE THREAD

**Issue by nmiodice** [lhz516/react-h5-audio-player#35]
I love this audio player! The only thing that I'm unable to accomplish is removing the border that shows up after clicking a button in the UI:

Before click:
![image](https://user-images.githubusercontent.com/2497673/79938260-c01af200-8421-11ea-8e38-5a28b2b3fbaf.png)

After click:
![image](https://user-images.githubusercontent.com/2497673/79938290-d032d180-8421-11ea-99ed-4044016c0507.png)

Is it possible to remove the blue border? I cannot find a style override.

**Comment by lhz516** [comment]
That browser default outline is for accessibility. For example, if a person can only use keyboard "Tab" key to navigate, they needs to know which button is currently focused.

If you don't want that, you can overwrite the style easily:
```css
.rhap_button-clear {
  outline: 0;
}

**Comment by nmiodice** [comment]
Wow, thank you! I did not know :)

**Comment by nmiodice** [comment]
For anyone that stumbles on this, I incorporated this with a material-UI project using this code:

```jsx
const useStyles = makeStyles((theme) => ({
  audioPlayer: {
    outline: 0,
    '& *': {
      outline: 0
    }
  },
}));

function getAudioPlayer(classes) {
  return (
    <AudioPlayer
      className={classes.audioPlayer}
      ...
    />
  );
}
```
