### ISSUE TITLE
Extra spacing in horizontal layout

### ISSUE THREAD

**Issue by JeffreyCA** [lhz516/react-h5-audio-player#36]
**Describe the bug**

I am using the component like this:

```js
<AudioPlayer
          src=""
          showJumpControls={false}
          customVolumeControls={[]}
          customAdditionalControls={[]}
          layout="horizontal"
        />
```
To me there's too much spacing around the play button.
<img width="427" alt="Screen Shot 2020-04-23 at 4 14 33 PM" src="https://user-images.githubusercontent.com/9157833/80151042-646a7900-8587-11ea-86a4-5e3910f9e9ec.png">

Package version: 3.0.5
React version: 16.13.1
Browser and its version: Chrome 83
OS and its version: macOS 10.15.5

**Comment by lhz516** [comment]
Currently `.rhap_progress-section` has `flex: 3 1 auto;` which makes it look good for most layouts.

The library cannot have styles that good for all custom layouts. I'd recommend you to overwrite it by:
```css
.rhap_progress-section {
  flex: 6 1 auto;
}
```
or 
```css
.rhap_controls-section {
  flex: 0;
}
```

**Comment by JeffreyCA** [comment]
Ok I'll do that.
