### ISSUE TITLE
Progress bar and volume bar knobs stick to cursor after right click

### ISSUE THREAD

**Issue by JeffreyCA** [lhz516/react-h5-audio-player#39]
Sorry to bombard you with all these issues I'm creating 😄, I really appreciate your work though!

Steps to reproduce:

1. Right click anywhere on the progress bar or volume bar
2. Dismiss the context menu (left-click somewhere on the page)
3. Move mouse cursor around

Observed:
The knob continues to follow the cursor until an additional left-click is registered.

Expected:
The knob should not follow the cursor.
 
This also happens if you Right click > Inspect Element instead of dismissing the menu.

Browser and its version: Chrome 83.0.4103.23
OS and its version: macOS 10.15.5 Beta (19F62f)

**Comment by lhz516** [comment]
No worries. Don't hesitate to report bugs. It's also contributing to the project!

I can't reproduce it on windows Chrome. Let me try it on mac tomorrow.

**Comment by lhz516** [comment]
I figured out that when right clicking the progressbar, `mouseup` event won't trigger even though we actually released the mouse key. That happens only on Mac Chrome

I used `preventDefault` on right click event to prevent the context menu. Please try `3.0.6`.

**Comment by JeffreyCA** [comment]
Thanks that fixed it! Closing the issue.
