### ISSUE TITLE
Playing multiple src at the same time

### ISSUE THREAD

**Issue by julian-aimusic** [lhz516/react-h5-audio-player#42]
Hey great package, I was wondering if you guys were thinking of implementing an array of src audio files to be played together, or even if this is currently possible?

Thanks for your time

**Comment by julian-aimusic** [comment]
by together I mean at the same time overlapped, I saw the playlist feature in the docs

**Comment by lhz516** [comment]
Hi, the package itself doesn't support playlist, but you can implement it externally.

Here's the examples: 
https://github.com/lhz516/react-h5-audio-player/blob/master/stories/playlist.tsx
https://github.com/lhz516/hanzluo/blob/9e21184cca732c1c38bc93a72e914b9dd28c69fe/src/components/home/home.js#L279
