### ISSUE TITLE
cannot override scss variable

### ISSUE THREAD

**Issue by didrip** [lhz516/react-h5-audio-player#43]
Hi, first thank you for this good player.

I am using [CRA](https://github.com/facebook/create-react-app) with `node-sass` and can't seem to find a way to override the SCSS variable.

I import the variables before `react-h5-audio-player` style like that :

```js
import 'globals.scss';
import 'react-h5-audio-player/src/styles.scss';
```

where in my global.scss file I have :

```scss
$rhap_theme-color: #000000;
```

So as I understand it it should override the one defined in `react-h5-audio-player/src/styles.scss` because it has the default flag.

What's wrong ?

**Comment by didrip** [comment]
Long story short :

```scss
$rhap_theme-color: #000000;
@import 'react-h5-audio-player/src/styles.scss';
```

**Comment by lhz516** [comment]
Hi. Looks like you closed the issue. Is it resolved?

**Comment by didrip** [comment]
Yes sorry if it was not clear. The import needs to be made from the SCSS file (global.scss in my example), not from the JS file. not an issue with `react-h5-audio-player` at all.
