### ISSUE TITLE
Auto Play Bug? Backspace -> command + s = Auto Play

### ISSUE THREAD

**Issue by SwftAlpc** [lhz516/react-h5-audio-player#44]
Hi, lhz516.
I was using this component with true autoplay status.
I was writing a program by starting VSCode with the screen displaying this component in the tab of the browser.

When I pressed ⌘ + s after pressing Backspace to fix and save the program, Auto Play happened.

Is this a bug?

Package version: 3.1.0
React version: 16.12.0
Browser and its version: Google Chrome 81.0.4044.138 (Official Build) (64 bit)
OS and its version: macOS Catalina 10.15.4

Thank You.

**Comment by lhz516** [comment]
It sounds like you are using a dev server that listens to your file changes, and re-build the bundle.
It will trigger the browser page to re-render, and the audio will auto play because the old `<audio>` tag is replaced by the new one.
