### ISSUE TITLE
Next Button not firing 

### ISSUE THREAD

**Issue by Deamoner** [lhz516/react-h5-audio-player#45]
**Describe the bug**

When I click the next button with the following code, no console long is sent. Additionally it only fast forwards 5 seconds. 
  ``` <AudioPlayer
      autoPlay
      loop
      footer
      ref={player}
      src="http://aivibes.s3.amazonaws.com/hip_hop/HipHop%20(10).mp3"
      onPlay={e => console.log("onPlay")}
      onClickNext={e => console.log("onNextClick")}
      onListen={e => console.log("onListenInterval")}
      onEnded={e => console.log("onEnd")}
      // other props here
    /> ````


My use case is I wanted to load an array of songs into the player for the next song, but arrays didn't seem to work, so I thought I can use the next and end of song events to load the next song. But neither or those events ever fire to run my functions.

**Comment by lhz516** [comment]
Hi, it's not reproducible on all my platforms. Could you follow the issue template to provide the info below?

Package version:
React version:
Browser and its version:
OS and its version:

Also, when you go to https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/story/actions--actions and click "Next" and "Previous" buttons, can you see the actions logged?
![image](https://user-images.githubusercontent.com/9879279/81488347-6b96b580-921c-11ea-8403-6ab0f4450df7.png)

For overwriting fast forward steps, you can use `progressJumpSteps` props as the README says.

**Comment by Deamoner** [comment]
I review your playlist sample. This shows the default is skip forward unless I enable the next button. Then your “next” or multi song functionality isn’t actually built in so you created playlist for that. I think I can see where my thinking differs now.

**Comment by lhz516** [comment]
Yea, the button you clicked was actually "Forward" button, that's why you didn't see logs with `onClickNext".

Closing.
