### ISSUE TITLE
onProgressBarClick to change the current  playing audio time

### ISSUE THREAD

**Issue by Badrouu17** [lhz516/react-h5-audio-player#48]

**Comment by lhz516** [comment]
Hi, could you clarify?

**Comment by Badrouu17** [comment]
> Hi, could you clarify?

Heyy, When I click on the progressBar it just replays the song. how can I make it change the audio progress to the point where the user clicked? ( like any progressBar supposed to work )

**Comment by lhz516** [comment]
Check out this issue https://github.com/lhz516/react-h5-audio-player/issues/32 . It''s probably because of the server settings
