### ISSUE TITLE
onClick event on play button

### ISSUE THREAD

**Issue by manang** [lhz516/react-h5-audio-player#49]
Hi, is there the onClick event on the play button?
Thank you very much

**Comment by lhz516** [comment]
We do have `onPlay` and `onPause` props. Check out the README

**Comment by manang** [comment]
Hi, my idea is the following:
the src is null and when I click on play I want to select the song in a list with a logic.
if the src is null I don't have the onplay event.
Thanks

**Comment by lhz516** [comment]
I see. You can pass `src=''` (don't use `null`), and `onPlayError` will be triggered when you click Play button

**Comment by manang** [comment]
thanks
