### ISSUE TITLE
event volume changed

### ISSUE THREAD

**Issue by manang** [lhz516/react-h5-audio-player#50]
Hi, I want to know if there is an event to manage the volume changed event.
in this way I can save the level and if I reload the page I don't have the max level volume.
Thank you very much
Angelo

**Comment by lhz516** [comment]
Good suggestion! I'll put it on the roadmap.

For now you can do this hack:
1. Get `audio` object using `ref`. See [Advanced Usage](https://github.com/lhz516/react-h5-audio-player#advanced-usage)
2. `audio.addEventListener('volumechange', () => { /* Do your stuff */ })`

**Comment by lhz516** [comment]
Published 3.2.0

Closing

**Comment by manang** [comment]
Thanks!
