### ISSUE TITLE
How does the player handle error responses

### ISSUE THREAD

**Issue by sanderdewijs** [lhz516/react-h5-audio-player#53]
A project I'm working on has temporary media URL's to prevent hotlinking to media sources. The media URL is valid for 70 minutes, and after this the media URL returns a 401. I noticed that the audio player keeps retrying to load the data instead of aborting. I added the onError to catch this event, and show a friendly message that the media URLhas expired. but it does not seem to catch the error response. Or do I need to use the onPlayError event instead?

Regards,
Sander

**Comment by SarhadSalam** [comment]
I had a similar need, what I ended up doing is:

1. Use onPlayError
2. After that's triggered, set the src to null/undefined
3. Notify the user that the event just failed

**Comment by lhz516** [comment]
Do you mean to get the response body like AJAX? I don't think if possible with audio API.

But we can get `MediaError` object by `e.target.error.code` in `onError`'s callback.
See https://developer.mozilla.org/en-US/docs/Web/API/MediaError
Name | Value | Description
-- | -- | --
MEDIA_ERR_ABORTED | 1 | The fetching of the associated resource was aborted by the user's request.
MEDIA_ERR_NETWORK | 2 | Some kind of network error occurred which prevented the media  from being successfully fetched, despite having previously been  available.
MEDIA_ERR_DECODE | 3 | Despite having previously been determined to be usable, an error  occurred while trying to decode the media resource, resulting in an  error.
MEDIA_ERR_SRC_NOT_SUPPORTED | 4 | The associated resource or media provider object (such as a MediaStream) has been found to be unsuitable.

**Comment by sanderdewijs** [comment]
It's not the content of the error response, just if there is an error, so I can abort gracefully. So this information is perfect! Thanks!

**Comment by lhz516** [comment]
Cool. Glad to help. Closing
