### ISSUE TITLE
Way to play and pause

### ISSUE THREAD

**Issue by vj-abishek** [lhz516/react-h5-audio-player#54]
## Way to play and pause     
I need to implement my own play and pause. In my app, I'm using a mini player and I'm hiding the main audio-player. At the mini-player, you can see the title and play, pause button.
If clicked on the mini player it shows the main audio player(react-h5-audio-player)

I'm using this to get the ref
 ```
this.player = createRef()
<ReactAudioPlayer ref={this.player} />
```
At the UI if pause button is clicked I'm using
`PlayerRef.current.audio.current.pause();` to pause the audio and it works
If clicked on the play button, I'm using
`PlayerRef.current.audio.current.play();` but at this time the player ref is null. Is there any way to persist the ref? or is there any other way to do it?

Thanks in advance!

**Comment by lhz516** [comment]
Did you remove the player element out of the DOM? If so, I suggest you to hide the player by css.

If it's not the case, could you make a minimum reproducable example based on this Codepen? https://codepen.io/lhz516/pen/dyGpmgP

**Comment by vj-abishek** [comment]
Sorry, I'm removing the element instead of hiding it. 

The thing I tried it here. 
`working CodeSandbox`
https://codesandbox.io/s/jolly-snow-swwc9

`Demo `
https://swwc9.csb.app/

Thanks this is an awesome Player.
