### ISSUE TITLE
Radio stream without caching

### ISSUE THREAD

**Issue by FReeeZzze** [lhz516/react-h5-audio-player#55]
Hello, is it possible to play a radio stream without caching? When you press the pause, the downloaded data is cached in the player, and after you press the start button, they are played from the moment of pause, and not what is played in the radio stream.

**Comment by lhz516** [comment]
It looks like you found the solution since you closed the issue.

I haven't considered the use case of playing a streamed audio. It would be great if you share your experience.

**Comment by FReeeZzze** [comment]
> It looks like you found the solution since you closed the issue.
> 
> I haven't considered the use case of playing a streamed audio. It would be great if you share your experience.

Yes, it seems like a temporary solution that I found, I used the <audio /> method of the load() tag to resume the stream, I had to make a separate button for play / pause, since load () is a replacement for onPlay ().
`  const onClick = () => {
    if (!status) player.current.audio.current.load();
    else player.current.audio.current.pause();
  };
  onPause={() => {
     setStatus(false);
  }}
`

**Comment by lhz516** [comment]
Ah, that's good walkaround. Thanks for sharing!
