### ISSUE TITLE
safari browser in desktop and ios device autoplay audio not working

### ISSUE THREAD

**Issue by kishan143-jaiswal** [lhz516/react-h5-audio-player#6]
<AudioPlayer
                        autoPlay
                        volume={false}  
                       src={this.state.src}
                        ref={(a) => this._audio = a}  
                    />
like this i have created component

**Comment by lhz516** [comment]
Unfortunately, `autoPlay` is blocked by Safari https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/

**Comment by kishan143-jaiswal** [comment]
Thanks for your comments..
