### ISSUE TITLE
Autoplay happens even when flag is false

### ISSUE THREAD

**Issue by Tatsianacs** [lhz516/react-h5-audio-player#60]
I have a List component which displays a list of options, let's say movie names. Once a movie is selected, details component should display audio player. The problem is that when I switch movies in the List, player starts autoplay although I specify autoplay as false or simply omit it. How can I prevent autoplay? 
In addition, console displays errors:
index.js:1 Uncaught Error: The error you provided does not contain a stack trace.
    at S (index.js:1)
    at V (index.js:1)
    at index.js:1
    at index.js:1
    at a (index.js:1)
S @ index.js:1
V @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
a @ index.js:1
react-dom.development.js:1350 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request. https://goo.gl/LdLk22

**Comment by lhz516** [comment]
You can set the hidden prop `autoPlayAfterSrcChange` to `false`. It will be added to README.

For the `Uncaught Error`, it seems like the promise is needed for all `audio.play()` and catch error properly. I'll fix it soon.

**Comment by Tatsianacs** [comment]
Thank you for your job

**Comment by lhz516** [comment]
Released 3.3.0 https://github.com/lhz516/react-h5-audio-player/releases/tag/v3.3.0

Closing the issue. Feel free to continue the discussion if needed.

**Comment by Tatsianacs** [comment]
Hi, I have installed 3.3.0 version and new bug is introduced: when switching items, icon 'pause' is shown instead of 'play' although nothing is being played (   autoPlayAfterSrcChange={false} )
I reverted to 3.2.0 and it works. So this bug is introduced in 3.3.0

**Comment by lhz516** [comment]
Thanks for reporting! Sorry for the inconvenience.

I removed some logic which I thought it was "useless".

I just added them back with some comments so that it won't be removed in the future. (See the referred commit above.)

Published 3.3.1, please try out
