### ISSUE TITLE
Scrub bar is broken when the page is horizontally scrolled

### ISSUE THREAD

**Issue by dapetcu21** [lhz516/react-h5-audio-player#61]
**Describe the bug**

The X offset of the touch position when clicking on the scrub bar is wrong when the page is scrolled horizontally by any amount. It's easily reproducible in the demo CodePen linked in the README. Just make the component wider and the browser window small, then scroll horizontally and try to scrub.

**Environment**

Package version: 3.3.0
React version: 16.13.1
Browser and its version: latest Chrome and Safari
OS and its version: macOS 10.15.6

**Comment by lhz516** [comment]
That is reproducible. Thanks for reporting. Will take a look.

**Comment by colinricardo** [comment]
This is probably why scrubbing on an iOS device is very hit or miss at the moment?

**Comment by lhz516** [comment]
Fixed and published `3.4.1`. Closing
