### ISSUE TITLE
Is there a way to get just the time/progress bar? 

### ISSUE THREAD

**Issue by colinricardo** [lhz516/react-h5-audio-player#62]
If I pass:
```
 customIcons={{
  play: null,
  pause: null,
}}
```

The play/pause icon still shows up. I presume this is by design. 

I want to control the player through other buttons on the UI. 

Would it be possible to add a hideAllControls param that hides everything except the time/progress bar?

**Comment by lhz516** [comment]
Try the prop `customControlsSection={[]}`

**Comment by colinricardo** [comment]
Nice, that works, thank you!
