### ISSUE TITLE
Support Media Source Extensions and EME 

### ISSUE THREAD

**Issue by SergioCrisostomo** [lhz516/react-h5-audio-player#63]
### This is a feature request question.

W3C defined specs for [Media Source Extensions](https://www.w3.org/TR/media-source/) and [Encrypted Media Extensions](https://www.w3.org/TR/encrypted-media/). This specification allows JavaScript to dynamically construct streams for `<audio>`. It defines a MediaSource object that can serve as a source of media data for an HTMLMediaElement, instead of just passing a URL.

There are more advanced players like DASH, HLS, Shaka, etc. These are very complex video players that can play audio if the audio format is following their standard (dash `.mpd` manifest, or HLS `.m3u8` manifest). But there is a use case for more simple and generic uses where the app using has its own logic for audio streams.

I think it would be good to be able to support the W3C standard in its most simple form, ie:
 - enabling the use of MSE
 - enabling Clear Key encryption events and callbacks

In practical terms this means:
 - adding a callback for EME events `encrypted`, `message`, `keystatuseschange`
 - adding mechanism to set the length display so we can show the track length
 - enable seek functionality
 - (maybe, not tested) correct the loaded progress bar to show properly the chunks that are loaded

I suggest minimal additions in the H5 player, as far as possible putting the MSE/EME logic on the consumer of the player. These changes would expand the use case of this player to consuming audio streams.

I am happy to implement this if you think might be useful. Happy to hear your thoughts.

**Comment by lhz516** [comment]
Thanks for the explanation.

Look like the work of adding new `props` is straight forward. The hardest part is loading chunks and connect them with the progress bar. The behavior would be very different from the existing progress bar. So I have one thing to discuss before you create a PR. Are you planning to create a new progress bar component and use it with SME; or modify the existing `ProgressBar` to support both?

**Comment by SergioCrisostomo** [comment]
Quite true, I am not sure the MSE api fires `progress` events the same way. I did check now and seems like it behaves the same way so the progress bar logic could stay untouched.

**Comment by lhz516** [comment]
I see. Sounds good to me! I'll give a review once you create a PR. Thanks for the initiative!
