### ISSUE TITLE
Option to seekTo

### ISSUE THREAD

**Issue by sterbon** [lhz516/react-h5-audio-player#65]
I want to add a button to seek to a specific point in the song with given value, any way to achieve that?

**Comment by lasoren** [comment]
is this possible?

**Comment by sterbon** [comment]
Yes, it is. 
To achieve this, you would need to create a reference for the player using `this.player = createRef()`, I used ReactJS, so I had to create this reference in `componentDidMount()` life cycle method. 
After you have the reference ready you can use `this.player.current.audio.current.currentTime = value` where value is the time in sec you want to seek to. 

You can `console.log` this.player to see all the options available.
