### ISSUE TITLE
Set authorization header audio src

### ISSUE THREAD

**Issue by ALogvinov** [lhz516/react-h5-audio-player#67]
My API (backend) require authorization to play audio.

Can I set authorization header to component src propertie?

**Comment by lhz516** [comment]
If there are cookies, they will be automatically sent with the request. But I don't think it supports custom headers.

Reference: https://security.stackexchange.com/questions/175695/how-to-pass-authorization-header-in-http-request-when-using-html5-player-audio

Let me know if I misunderstood something

**Comment by lhz516** [comment]
Closing. Feel free to reopen if you have more details to provide
