### ISSUE TITLE
Only show the player/stop button

### ISSUE THREAD

**Issue by rodbs** [lhz516/react-h5-audio-player#68]
Hello,

Is there a way to only show the player/stop button?  I've got to remove all but the progress bar and the time counters.

Thx

**Comment by lhz516** [comment]
Hi, here's an example:
```jsx
import AudioPlayer, { RHAP_UI } from 'react-h5-audio-player'

const Player = () => (
  <AudioPlayer
    src="..."
    customControlsSection={[RHAP_UI.MAIN_CONTROLS]}
    customProgressBarSection={[]}
    showJumpControls={false}
  />
)
```
Docs for advanced layout:
https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts-advanced--stacked

**Comment by rodbs** [comment]
It works nicely. Thanks

**Comment by lhz516** [comment]
No problem. Closing.
