### ISSUE TITLE
How to encrypted Audio file ?

### ISSUE THREAD

**Issue by sumit151199** [lhz516/react-h5-audio-player#69]
I found to difficulties to setup Please suggest me. @lhz516

**Comment by lhz516** [comment]
If you are refering EME, here's an example https://github.com/lhz516/react-h5-audio-player/blob/master/stories/mse-eme-player.tsx

If not, please provide more details of your question.

**Comment by sumit151199** [comment]
1. How to use this example? 
2.  when I'm calling **<MediaSourcePlayer onEncrypted={action('onEncrypted')} />** showing **"action' is not defined"** How and from  import action.
3. I want to disable forward button ?
Thank you @lhz516

**Comment by lhz516** [comment]
1. The question is too general. Basically this example is showing how to use it.

2. That `action` is for storybook action logger usage only, please ignore that and just read the example I posted above

3. If you mean to hide it, you can try `showJumpControls={false}`; if you mean the `disable` attribute on the button, we currently don't support it. I may consider adding it in the future.

**Comment by sumit151199** [comment]
I'm using this example audio is not play with encrypted file or non encrypted file . Without encryption audio played successfully.
Thank you @lhz516

**Comment by lhz516** [comment]
When you locally run storybook, you need to run the assets server first:
```
node stories/assets-server/server.js
```
and then run the storybook in another terminal:
```
yarn storybook
```

**Comment by sumit151199** [comment]
1. I want to add audio wave according to the audio  , Is this possible? 
2. last  suggestion not working
Thank you @lhz516

**Comment by lhz516** [comment]
1. No. It's out of the project's scope

2. If you do these steps and go to storybook -> MSE-EME -> Play encrypted audio -> Click play button. I tried it just now
![image](https://user-images.githubusercontent.com/9879279/94346356-0849cc00-ffe1-11ea-9772-0c5c24230ca8.png)

If it's not working for you. Please provide more details.
