### ISSUE TITLE
safari browser desktop drag function not working 

### ISSUE THREAD

**Issue by kishan143-jaiswal** [lhz516/react-h5-audio-player#7]
i have used this library ,its worked fine in all the browsers of desktop and mobile devices but safari browser drag function not working

**Comment by lhz516** [comment]
Thanks for reporting. I didn't test MacOS Safari because I use PC at home.
I'll find a chance to debug it with my MacBook sometime. (PR is also appreciated)

**Comment by lhz516** [comment]
Fixed. Try 2.x. It's using `mousedown/move/up` instead of dragging events
