### ISSUE TITLE
timeStamp in "timeupdate" event seems random

### ISSUE THREAD

**Issue by Evanfeenstra** [lhz516/react-h5-audio-player#71]
Hello, on the onListen handler, the event.timeStamp seems to be totally random. It's returning numbers that dont match the actual timestamp of the audio file

**Comment by lhz516** [comment]
If you want to get the audio's duration and current time, you should use `event.target.duration` and `event.target.currentTime`.

The `event.target` refers to the [audio object](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) in this case and all other onXXX events.

**Comment by Evanfeenstra** [comment]
thank you! works perfectly
