### ISSUE TITLE
how to increase or decrease the speed of the audio?

### ISSUE THREAD

**Issue by jcvegan** [lhz516/react-h5-audio-player#72]
For a requirement, I want the player to handle the speed of the audio.

I understand that I can add custom controls, but how to access the sound itself to manipulate the sound?

**Comment by lhz516** [comment]
You can use `ref` to access the audio instance and modify `audio.playbackRate`

See https://github.com/lhz516/react-h5-audio-player#access-to-the-audio-element

**Comment by jcvegan** [comment]
Awesome, thanks for your response.
