### ISSUE TITLE
How to Disable onClick onProgress Bar?

### ISSUE THREAD

**Issue by sumit151199** [lhz516/react-h5-audio-player#73]

**Comment by sumit151199** [comment]
I want disable onClick on progress bar . Please Help

**Comment by lhz516** [comment]
Do you mean that you don't want to adjust the audio's current time when clicking on progress bar?

Currently, there's no support for that, but this is a reasonable feature request, I can imagine some usecases.

Let me put this on the roadmap.

**Comment by sumit151199** [comment]
> Do you mean that you don't want to adjust the audio's current time when clicking on progress bar?
> 
> Currently, there's no support for that, but this is a reasonable feature request, I can imagine some usecases.
> 
> Let me put this on the roadmap.


I mean to say that user can not forward / backward click on progress bar , Disabled click on progress bar
Thank you

**Comment by lhz516** [comment]
> I mean to say that user can not forward / backward click on progress bar , Disabled click on progress bar

Yea, that's what I mean as well. I put this on the roadmap, probably a new prop called `disableProgressControl` or something

**Comment by sumit151199** [comment]
> disableProgressControl
By Using this prop I can disable click  on progress bar? in future? 
Thank you

**Comment by sumit151199** [comment]
> > I mean to say that user can not forward / backward click on progress bar , Disabled click on progress bar
> 
> Yea, that's what I mean as well. I put this on the roadmap, probably a new prop called `disableProgressControl` or something

disableProgressControl
By Using this prop I can disable click on progress bar? in future?
Thank you

**Comment by sumit151199** [comment]
> > > I mean to say that user can not forward / backward click on progress bar , Disabled click on progress bar
> > 
> > 
> > Yea, that's what I mean as well. I put this on the roadmap, probably a new prop called `disableProgressControl` or something
> 
> disableProgressControl
> By Using this prop I can disable click on progress bar? in future?
> Thank you

disableProgressControl
By Using this prop I can disable click on progress bar? in future?
Thank you

**Comment by lhz516** [comment]
> By Using this prop I can disable click on progress bar? in future?

Yes. Let's keep this issue open until this feature is done

**Comment by sumit151199** [comment]
> > By Using this prop I can disable click on progress bar? in future?
> 
> Yes. Let's keep this issue open until this feature is done

Hi @lhz516  ,
 I need that feature ASAP , Can you please add  this feature  on priority .
Thank You

**Comment by lhz516** [comment]
@sumit151199  It's an uncommon feature that I would treat it as a low priority task.
If it's important to your project, feel free to help contribute to this lib.

**Comment by sumit151199** [comment]
> @sumit151199 It's an uncommon feature that I would treat it as a low priority task.
> If it's important to your project, feel free to help contribute to this lib.

Yes it's important for me, ca you please help

**Comment by lhz516** [comment]
After my reconsideration, this feature is deprioritized. Closing for now.

**Comment by Bilb** [comment]
For the time being, we can use the style{{}} attribute to set pointerEvents: none on the progress bar
