### ISSUE TITLE
onListen event issue in firefox.

### ISSUE THREAD

**Issue by h3is3nb3rg-cs** [lhz516/react-h5-audio-player#74]
Hi,
I am using onListen function to console the currentTime by accessing `event.path[0].currentTime` . 
The function works perfectly in google chrome. but in fireFox the `event` object does not have `path` property and I am unable to access the curenttime. I am not sure if this is an issue or I'm accessing the object in the wrong way.

Thanks

**Comment by lhz516** [comment]
Hi! Could you try `event.target.currentTime` ?

**Comment by h3is3nb3rg-cs** [comment]
I tried accessing the ref of the player and got current time by `audioRef.current.audio.current.currentTime` . It works in both chrome and firefox now.

anyways Thanks for the help.

**Comment by lhz516** [comment]
Using ref definitely works. And the `event.target` in an event handler should also refer to the audio object, isn't it?
