### ISSUE TITLE
Volume Bar Fill

### ISSUE THREAD

**Issue by l0gicgate** [lhz516/react-h5-audio-player#78]
Would it be possible to add volume bar fill? The progress bar fills up as it progresses, it would be nice to fill the volume bar as well to show the level and have uniformity with the progress bar.

See how the track progress is green? It would be nice to have that for volume as well. Otherwise it looks odd.

<img alt="screenshot" src="https://puu.sh/GOOdd/222da817c8.png" />

Thank you

**Comment by lhz516** [comment]
Sounds reasonable. Putting it on the roadmap.

**Comment by l0gicgate** [comment]
Thank you @lhz516 I would actually love to help if you need!

**Comment by lhz516** [comment]
@l0gicgate That would be great! PRs are welcome.

**Comment by lhz516** [comment]
Closing. Published 3.5.0

Will update the release note soon

**Comment by l0gicgate** [comment]
Thank you so much for the quick turnaround on this @lhz516! I appreciate it a lot!
