### ISSUE TITLE
player autoPlay prop not working

### ISSUE THREAD

**Issue by kishan143-jaiswal** [lhz516/react-h5-audio-player#8]
onload of player I want to stop autoPlay , but its not working as expected

**Comment by lhz516** [comment]
I don't see this issue. Could you submit your system env, browser and steps to reproduce?

**Comment by kishan143-jaiswal** [comment]
<AudioPlayer
          hidePlayer={this.state.hideShowPlayer}
          src={this.state.src}
          controls={true}
          autoPlay={false}
          ref={(a) => this._audioo = a}
      />
i have used like this in my child component ,onClick from parent i call this component and its directly start playing

**Comment by kishan143-jaiswal** [comment]
<AudioPlayer
          autoPlay
          src="" //any url
          onPlay={e => console.log("onPlay")}
        />
https://build.narendrachouhan0021.now.sh/
hosted demo of your library on Now and tested, its not autoPlaying on load,check the upper link

**Comment by lhz516** [comment]
Check your browser permission by clicking the icon on the left side of address bar.

Chrome:
![image](https://user-images.githubusercontent.com/9879279/58855109-032a7600-8654-11e9-9b9e-dcd49c525cde.png)

FireFox:
![image](https://user-images.githubusercontent.com/9879279/58855190-4b499880-8654-11e9-98e1-340e928f4d36.png)

**Comment by kishan143-jaiswal** [comment]
thanks it worked..

**Comment by daniyalMongotel** [comment]
How did you fix the issue? I have sound Automatic(default) and still the sound is auto playing when ever I re-render the page.. The sounds did not play when the pages is refreshed..

**Comment by canberkvarli** [comment]
Thank you for the solution.

**Comment by bob83727** [comment]
hi, I am also experiencing the same issue as @daniyalMongotel, autoplaying when re-render but not autoplay when refreshed, is there any solutions? I've tried turn off the sound permission of browser, but this just block the "sound" itself, which means the progress bar is still running, and the autoplay process seems still happened, you just won't hear the voice.

**Comment by gianatiempo** [comment]
For future reference, i was having the same issue as @daniyalMongotel  and @bob83727 and i solved it using:

` autoPlayAfterSrcChange={false}`
