### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Aneri12345** [lhz516/react-h5-audio-player#86]
Could you please answer the following:
1. How to remove the loop icon completely?
2. How to align the play button in the center?

**Comment by lhz516** [comment]
1. Use prop `customAdditionalControls={[]}`
2. Isn't the play button already centered? Please clarify.

**Comment by Aneri12345** [comment]
1. This solution worked. 
2. Yes it is, my bad.
Thank you : )

**Comment by Aneri12345** [comment]
The player, once paused, does not play again in Mozilla firefox.
Could you direct me regarding this compatibility issue?

**Comment by lhz516** [comment]
Could you fork this codepen and reproduce the issue? https://codepen.io/lhz516/pen/dyGpmgP

**Comment by Aneri12345** [comment]
Last few more questions
1. What if I want to shift some element to left or right (specifically the play button)
2. After I shift my button to the left, I will need to add the required extra elements in the center. Will this code help (                              customAdditionalControls={[]}> ) ?
3. How to increase play button size
 
At last thank you for solving the queries. It has been really helpful

**Comment by lhz516** [comment]
1 2. For customize the layout, please refer to [Advanced Layout](https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts-advanced--stacked). I believe `customControlsSection={[MAIN_CONTROLS, ADDITIONAL_CONTROLS, VOLUME_CONTROLS]}` will switch the positions and make the play button to the left side..

3. You can overwrite `rhap_play-pause-button` class, change all `40px`s to a larger number.
```css
.rhap_play-pause-button {
    font-size: 40px;
    width: 40px;
    height: 40px;
}
```
I'm planning to make this a SASS/LESS variable in a future release.

**Comment by Aneri12345** [comment]
Okay got it, it works.

All the best for your plans :)

**Comment by lhz516** [comment]
I just tried the css and it worked. You must change all `font-size`, `width` and `height` to the same value together.

**Comment by lhz516** [comment]
Closing now. Reopen if more discussion is needed.
