### ISSUE TITLE
Show Audio Details

### ISSUE THREAD

**Issue by fxhassan** [lhz516/react-h5-audio-player#87]
Can you add the ability to show Audio Details (i.e. The name of the track / a small picture to go with it )

**Comment by lhz516** [comment]
Hi, this feature is too specific for this library. I recommend you to try [custom layout](https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts-advanced--stacked) to find a way to add pictures and track names.
