### ISSUE TITLE
Seek events are missing!!

### ISSUE THREAD

**Issue by PrakashPaul** [lhz516/react-h5-audio-player#89]
I am trying to trace seek events for react-h5-audio-player, but looks like for few controls no event exposed.
Forward and Rewind button click events not available or documented
onProgressBarClick() event not triggering 
onDrag events also not available for audio progress bar

any help will be appreciated !

**Comment by lhz516** [comment]
Good suggestion. I'm planning to add all of these events as props: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

And transform them to onXXX such as: `seeked` -> `onSeeked`

**Comment by lhz516** [comment]
@PrakashPaul By the way, before we have this prop, you can use ref to add an event listener.
```js
audio.current.addEventListener('seeked', function() {})
```

**Comment by lhz516** [comment]
Done with https://github.com/lhz516/react-h5-audio-player/commit/3633d8480b96c7a51de6f4b8cbd137cd560c1d1b . Closing
