### ISSUE TITLE
audio play automatically on `src` change with unique URL but same audio when `autoPlay` is `false`

### ISSUE THREAD

**Issue by gencer** [lhz516/react-h5-audio-player#9]
https://github.com/lhz516/react-h5-audio-player/blob/b3497ed79c2c0f07cb31e6c8d314efc2a592138e/src/index.js#L328

In here, if `src` changes, audio gets played auto even we say `autoPlay` is `false`.

We should either add one more condition like `... && autoPlay` or completely disable this feature. Otherwise, in some cases, audios get played all the time.

**For example**; I regularly update components and when components updated, links get refreshed. Audio is **same** but each time update made, there is an **unique encoded URL for each audio**. So, with default, even if i select to not play audio automatically, its get played by this library because of this condition.

I've removed this on my repository and point the package there. I can create PR for this, if you want.

Just let me know which path should we follow here:

- a. adding one more condition
- b. completely remove this line

**Comment by mkorevec** [comment]
I was forced to mitigate this issue as well, at this point it would make sense to create a fork and a new npm package. Especially since it has been months without updates or comments.

**Comment by gencer** [comment]
Currently, I am using my own fork as;

```
"react-h5-audio-player": "https://github.com/gencer/react-h5-audio-player#master",
```

However, I will publish a npm package for this.

**Comment by lhz516** [comment]
Hi, please try the latest version and see if it's fixed. Thanks to @shannon-hibbett-m3 

BTW, I'm working on V2.0.0, here are the features I'm proposing, feel free to comment if you have any thoughts https://github.com/lhz516/react-h5-audio-player/issues/18

**Comment by lhz516** [comment]
I re-considered this issue.

`autoPlay` actually means auto play when first time DOM is loaded, not means every time `src` changes.

So I added another prop `autoPlayAfterSrcChange` which defaults to `true` because most music players are like this behavior.

**Comment by Nicholas-Lin** [comment]
This actually helped me a lot, thanks for adding it!

**Comment by sarahbock** [comment]
Thanks for adding `autoPlayAfterSrcChange`. Was crucial to getting my app working

**Comment by blessme247** [comment]
Thanks for adding autoPlayAfterSrcChange, it helped my app to stop auto playing. I would recommend that the autoPlayAfterSrcChange prop should be included on the npmjs page for easy reference for people who would probably encounter the issue in future.
