### ISSUE TITLE
How to make media queries for the player?

### ISSUE THREAD

**Issue by rllstpwz** [lhz516/react-h5-audio-player#97]
Is there any way to make a media query for the player css, since making one doesn't seem to work: 
`  @media screen and (max-width: 900px) {
    .rhap_container {
        width: 90%;
    }
    
}  `

**Comment by lhz516** [comment]
It should be the correct way. I just tried and it worked.

![image](https://user-images.githubusercontent.com/9879279/110233700-94d6af80-7eda-11eb-8874-b40da752d4ec.png)
