### ISSUE TITLE
event on loop on/off click

### ISSUE THREAD

**Issue by eGene** [lhz516/react-h5-audio-player#99]
As far as I can see there is no event firing when user clicks Loop icon to enable or disable loop. Can it be replaced with some other event? That is needed in order to create controlled player component.

**Comment by lhz516** [comment]
You may want to use `customAdditionalControls` prop to hide the loop button and [make your custom button](https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts-advanced--custom-additional-controls).
